<?php

$modversion['name'] = _MI_CREVIEW_NAME;
$modversion['version'] = 1.00;
$modversion['description'] = _MI_CREVIEW_DESC;
$modversion['author'] = 'Sam Chang & Duc Nguyen';
$modversion['help'] = 'creview.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 1;
$modversion['image'] = 'images/cr_logo.gif';
$modversion['dirname'] = 'course_review';
// $modversion['dirname'] = "courseReview";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)

// All tables should not have any prefix!

$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix)

$modversion['tables'][0] = 'cr_reviews';

$modversion['tables'][1] = 'cr_depts';

$modversion['tables'][2] = 'cr_courses';

$modversion['tables'][3] = 'cr_profs';

$modversion['tables'][4] = 'cr_ratings';

$modversion['tables'][5] = 'cr_reporting';

// Admin things

$modversion['hasAdmin'] = 1;

$modversion['adminindex'] = 'admin/index.php';

$modversion['adminmenu'] = 'admin/menu.php';

$modversion['blocks'][1]['file'] = 'featured.php';

$modversion['blocks'][1]['name'] = 'Featured Reviews';

$modversion['blocks'][1]['description'] = 'Shows featured reviews';

$modversion['blocks'][1]['show_func'] = 'cr_show_featured';

//$modversion['blocks'][1]['edit_func'] = "b_myreviews_top_edit";
//$modversion['blocks'][1]['options'] = "date|10|25";

$modversion['blocks'][2]['file'] = 'newest.php';

$modversion['blocks'][2]['name'] = 'Newest Reviews';

$modversion['blocks'][2]['description'] = 'Shows most recently added reviews';

$modversion['blocks'][2]['show_func'] = 'cr_show_newest';

$modversion['blocks'][2]['edit_func'] = 'cr_edit_latest';
# options[0] - char limit
# options[1] - row limit
$modversion['blocks'][2]['options'] = '50|10';
$modversion['blocks'][2]['template'] = 'crv_block_newest.html';

$modversion['blocks'][3]['file'] = 'profsearch.php';

$modversion['blocks'][3]['name'] = 'Search for Professors';

$modversion['blocks'][3]['description'] = 'Search for Professor Reviews';

$modversion['blocks'][3]['show_func'] = 'cr_show_profsearch';

//$modversion['blocks'][3]['edit_func'] = "b_myreviews_top_edit";

//$modversion['blocks'][3]['options'] = "hits|10|25";

$modversion['blocks'][4]['file'] = 'coursesearch.php';

$modversion['blocks'][4]['name'] = 'Search for Courses';

$modversion['blocks'][4]['description'] = 'Search for Course Reviews';

$modversion['blocks'][4]['show_func'] = 'cr_show_coursesearch';

//$modversion['blocks'][4]['edit_func'] = "b_myreviews_top_edit";

//$modversion['blocks'][4]['options'] = "hits|10|25";

// Menu

$modversion['hasMain'] = 1;

$modversion['sub'][1]['name'] = 'Add a review';

$modversion['sub'][1]['url'] = 'add.php';

$modversion['sub'][2]['name'] = 'Search reviews';

$modversion['sub'][2]['url'] = 'search.php';

// Search

$modversion['hasSearch'] = 1;

$modversion['search']['file'] = 'include/search.inc.php';

$modversion['search']['func'] = 'myReviews_search';

// Comments

$modversion['hasComments'] = 1;

$modversion['comments']['pageName'] = 'showreview.php';

$modversion['comments']['itemName'] = 'rev_id';

// Comment callback functions

$modversion['comments']['callbackFile'] = 'include/comment_functions.php';

$modversion['comments']['callback']['update'] = 'cr_com_update';

$modversion['comments']['callback']['approve'] = 'cr_com_approve';

// Templates

$modversion['templates'][1]['file'] = 'showreview.html';

$modversion['templates'][1]['description'] = 'Review detail';

$modversion['templates'][2]['file'] = 'start_form.html';

$modversion['templates'][2]['description'] = '';

$modversion['templates'][3]['file'] = 'handleadd.html';

$modversion['templates'][3]['description'] = '';

$modversion['templates'][4]['file'] = 'course_reviews.html';
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = 'course_overview.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'course_review.html';
$modversion['templates'][6]['description'] = '';
$modversion['templates'][7]['file'] = 'course_specs.html';
$modversion['templates'][7]['description'] = '';
$modversion['templates'][8]['file'] = 'course_useropinions.html';
$modversion['templates'][8]['description'] = '';
$modversion['templates'][9]['file'] = 'professor_overview.html';
$modversion['templates'][9]['description'] = '';
$modversion['templates'][10]['file'] = 'professor_admin_review.html';
$modversion['templates'][10]['description'] = '';
$modversion['templates'][11]['file'] = 'professor_user_reviews.html';
$modversion['templates'][11]['description'] = '';
$modversion['templates'][12]['file'] = 'professors_list.html';
$modversion['templates'][12]['description'] = '';
$modversion['templates'][13]['file'] = 'professors_photos.html';
$modversion['templates'][13]['description'] = '';

$modversion['config'][1]['name'] = 'maxfilesize';

$modversion['config'][1]['title'] = '_MI_CR_FILESIZE';

$modversion['config'][1]['description'] = 'Max filesize';

$modversion['config'][1]['formtype'] = 'textbox';

$modversion['config'][1]['valuetype'] = 'int';

$modversion['config'][1]['default'] = 80000;

$modversion['config'][2]['name'] = 'uploaddir';

$modversion['config'][2]['title'] = '_MI_CR_UPLOADDIR';

$modversion['config'][2]['description'] = '';

$modversion['config'][2]['formtype'] = 'textbox';

$modversion['config'][2]['valuetype'] = 'text';

$modversion['config'][2]['default'] = 'modules/' . $modversion['dirname'] . '/uploads';

$modversion['config'][3]['name'] = 'mimetypes';

$modversion['config'][3]['title'] = '_MI_CR_MIMETYPES';

$modversion['config'][3]['description'] = '';

$modversion['config'][3]['formtype'] = 'select_multi';

$modversion['config'][3]['valuetype'] = 'array';

$modversion['config'][3]['default'] = ['doc', 'pdf', 'html', 'txt', 'rtf', 'txt'];

$modversion['config'][3]['options'] = [
            '---------------------------' => 'none',

            'doc' => 'application/msword',

            'pdf' => 'application/pdf',

            'html' => 'text/html',

            'txt' => 'text/plain',

            'rtf' => 'text/rtf',

            'oct' => 'application/octet-stream',
];

$modversion['config'][4]['name'] = 'img_maxfilesize';

$modversion['config'][4]['title'] = '_MI_CR_IMG_FILESIZE';

$modversion['config'][4]['description'] = 'Max filesize';

$modversion['config'][4]['formtype'] = 'textbox';

$modversion['config'][4]['valuetype'] = 'int';

$modversion['config'][4]['default'] = 80000;

$modversion['config'][5]['name'] = 'img_mimetypes';

$modversion['config'][5]['title'] = '_MI_CR_IMG_MIMETYPES';

$modversion['config'][5]['description'] = '';

$modversion['config'][5]['formtype'] = 'select_multi';

$modversion['config'][5]['valuetype'] = 'array';

$modversion['config'][5]['default'] = ['bmp', 'gif', 'jpeg', 'png'];

$modversion['config'][5]['options'] = [
            '---------------------------' => 'none',

            'bmp' => 'image/bmp',

            'gif' => 'image/gif',

            'ief' => 'image/ief',

            'jpeg' => 'image/pjpeg',

            'jpg' => 'image/jpeg',

            'png' => 'image/x-png',

            'tiff' => 'image/tiff',

            'tif' => 'image/tif',

            'ico' => 'image/icon',

            'djvu' => 'image/vnd.djvu',

            'djv' => 'image/vnd.djvu',

            'wbmp' => 'image/vnd.wap.wbmp',

            'ras' => 'image/x-cmu-raster',

            'pnm' => 'image/x-portable-anymap',

            'pbm' => 'image/x-portable-bitmap',

            'pgm' => 'image/x-portable-graymap',

            'ppm' => 'image/x-portable-pixmap',
];

$modversion['config'][6]['name'] = 'list_limit';

$modversion['config'][6]['title'] = '_MI_CR_LIST_LIMIT';

$modversion['config'][6]['description'] = '';

$modversion['config'][6]['formtype'] = 'select';

$modversion['config'][6]['valuetype'] = 'int';

$modversion['config'][6]['default'] = 10;

$modversion['config'][6]['options'] = [
            '5' => 5,

            '10' => 10,

            '15' => 15,

            '20' => 20,
];

$modversion['config'][7]['name'] = 'char_limit';

$modversion['config'][7]['title'] = '_MI_CR_CHAR_LIMIT';

$modversion['config'][7]['description'] = '';

$modversion['config'][7]['formtype'] = 'select';

$modversion['config'][7]['valuetype'] = 'int';

$modversion['config'][7]['default'] = 25;

$modversion['config'][7]['options'] = [
            '20' => 20,

            '30' => 30,

            '40' => 40,

            '50' => 50,

            '60' => 60,

            '70' => 70,

            '80' => 80,

            '90' => 90,

            '100' => 100,
            ];

#$modversion['config'][3]['name'] = 'comment_rules';

#$modversion['config'][3]['title'] = 'Comment Rules';

#$modversion['config'][3]['description'] = '';

#modversion['config'][3]['formtype'] = 'yesno';

#$modversion['config'][3]['valuetype'] = 'int';

#$modversion['config'][3]['default'] = 0;

/*

$modversion['config'][4]['name'] = 'anonymous_comments';

$modversion['config'][4]['title'] = 'Allow anonymous post in comments?';

$modversion['config'][4]['description'] = '';

$modversion['config'][4]['formtype'] = 'yesno';

$modversion['config'][4]['valuetype'] = 'int';

$modversion['config'][4]['default'] = 0;



$modversion['config'][5]['name'] = 'notification';

$modversion['config'][5]['title'] = 'Enable Notification';

$modversion['config'][5]['description'] = '';

$modversion['config'][5]['formtype'] = 'yesno';

$modversion['config'][5]['valuetype'] = 'int';

$modversion['config'][5]['default'] = 0;



$modversion['config'][6]['name'] = 'spec_events';

$modversion['config'][6]['title'] = 'Enable Specific Events';

$modversion['config'][6]['description'] = '';

$modversion['config'][6]['formtype'] = 'yesno';

$modversion['config'][6]['valuetype'] = 'int';

$modversion['config'][6]['default'] = 0;

*/



